openapi: 3.0.0
info:
  title: Single Task Callback Reuse
  version: "0.0.1"
paths:
  /v1/tasks:
    post:
      summary: Submit single task with callback reuse
      description: >
        Checks Redis for (task_id + task_name) successful stage with non-empty output.
        On hit: return completed with reuse_info and skip scheduling.
        On pending/running: return pending with reuse_info.state=pending without scheduling.
        On miss/failed/empty: enqueue execution and accumulate stages without overwriting others.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [task_name, task_id, input_data]
              properties:
                task_name:
                  type: string
                  example: ffmpeg.extract_audio
                task_id:
                  type: string
                  example: task-demo-001
                callback:
                  type: string
                  format: uri
                  example: http://localhost:5678/webhook/demo-t1
                input_data:
                  type: object
      responses:
        "200":
          description: Created or reuse hit/wait
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id:
                    type: string
                  status:
                    type: string
                    description: completed | pending
                  reuse_info:
                    type: object
                    properties:
                      reuse_hit:
                        type: boolean
                      task_name:
                        type: string
                      source:
                        type: string
                        example: redis
                      cached_at:
                        type: string
                        format: date-time
                      state:
                        type: string
                        description: pending when waiting existing execution
                  result:
                    type: object
                    description: Full WorkflowContext when reuse hit completed
  /v1/tasks/{task_id}/status:
    get:
      summary: Query task status with accumulated stages
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: WorkflowContext with all stages
          content:
            application/json:
              schema:
                type: object
                properties:
                  workflow_id:
                    type: string
                  stages:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        status:
                          type: string
                        input_params:
                          type: object
                        output:
                          type: object
                        error:
                          type: object
                        duration:
                          type: number
                  error:
                    type: object
