openapi: 3.0.0
info:
  title: Single Task Cache Data Filtering
  version: "0.0.1"
  description: API contract for filtered cache reuse response in single-task mode.
paths:
  /v1/tasks:
    post:
      summary: Submit single task and get filtered cached result if available
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  task_id:
                    type: string
                  status:
                    type: string
                    example: completed
                  reuse_info:
                    type: object
                  result:
                    $ref: '#/components/schemas/FilteredWorkflowContext'
components:
  schemas:
    FilteredWorkflowContext:
      type: object
      properties:
        workflow_id:
          type: string
        status:
          type: string
        stages:
          type: object
          description: Only contains the stage matching the request task_name
          additionalProperties:
            $ref: '#/components/schemas/StageInfo'
    StageInfo:
      type: object
      properties:
        status:
          type: string
        output:
          type: object
